gemfile:
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
install:
  - 'travis_retry bundle install'
  - 'travis_retry bundle exec appraisal'
language:
  - ruby
rvm:
  - 2.2.4
sudo: false
cache: bundler
services:
  - postgresql
env:
  global:
    - DB=postgresql
    - DUMMY_DATABASE_USERNAME=postgres
    - DUMMY_DATABASE_PASSWORD=''
    - DATABASE_URL='postgres://localhost:5432'
bundler_args: --without development vagrant
script:
  - bundle exec appraisal rake db:create db:migrate db:seed RAILS_ENV=development
  - bundle exec appraisal rake db:schema:load RAILS_ENV=test
  - bundle exec appraisal rake spec
before_script:
  - sh -c "if [ '$DB' = 'postgresql' ]; then psql -c 'DROP DATABASE IF EXISTS ajax_validator_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgresql' ]; then psql -c 'CREATE DATABASE ajax_validator_test;' -U postgres; fi"
#  - sh -c "if [ '$DB' = 'postgresql' ]; then psql -c 'CREATE USER ajax_validator;' -U postgres; fi"
#notifications:
  #webhooks:
  #  urls:
  #    - https://webhooks.gitter.im/e/<add webhook id here>
  #  on_success: change
  #  on_failure: always
  #  on_start: false
#after_success:
  #- bash <(curl -s https://codecov.io/bash)
  #- ./deploy_snapshot.sh
#before_install:
#  - chmod +x ./deploy_snapshot.sh
